name: broadcast_stream_subscriber
description: >-
  A mixin with a minimal set of methods to add
  and manage StreamSubscriptions on any class.
version: 0.1.0+2
homepage: https://github.com/james-alex/broadcast_stream_subscriber

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5
  effective_dart: ^1.2.1
